import type { Job } from './types';

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    companyId: 'comp-1',
    companyName: 'Innovate Inc.',
    postedBy: 'recruiter-1',
    title: 'Frontend Developer',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'IT',
    requiredSkills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    location: { city: 'Pune', remoteAllowed: true },
    salaryRange: { min: 800000, max: 1200000, currency: 'INR' },
    description: 'Join our team to build beautiful and performant web applications.',
    openings: 2,
    screeningQuestions: ['What is your favorite React feature and why?'],
    isActive: true,
    createdAt: {} as any, 
    updatedAt: {} as any,
  },
  {
    id: 'job-2',
    companyId: 'comp-2',
    companyName: 'DataDriven Co.',
    postedBy: 'recruiter-2',
    title: 'Data Scientist',
    roleType: 'full-time',
    experienceLevel: '3+',
    domain: 'Data Science',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch', 'SQL'],
    location: { city: 'Bangalore', remoteAllowed: false },
    description: 'Work on cutting-edge machine learning models for our platform.',
    openings: 1,
    screeningQuestions: ['Describe a challenging data project you have worked on.'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-3',
    companyId: 'comp-3',
    companyName: 'Creative Solutions',
    postedBy: 'recruiter-3',
    title: 'UX/UI Designer Intern',
    roleType: 'internship',
    experienceLevel: 'fresher',
    domain: 'Design',
    requiredSkills: ['Figma', 'Adobe XD', 'User Research'],
    location: { city: 'Remote', remoteAllowed: true },
    salaryRange: { min: 20000, max: 25000, currency: 'INR' },
    description: 'A great opportunity for a creative mind to learn and grow.',
    openings: 3,
    screeningQuestions: ['Share your portfolio link.', 'What design principle is most important to you?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-4',
    companyId: 'comp-1',
    companyName: 'Innovate Inc.',
    postedBy: 'recruiter-1',
    title: 'Backend Engineer (Node.js)',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'IT',
    requiredSkills: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    location: { city: 'Pune', remoteAllowed: true },
    salaryRange: { min: 900000, max: 1400000, currency: 'INR' },
    description: 'Build and maintain the backbone of our services.',
    openings: 1,
    screeningQuestions: [],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
];
