import type { Job } from './types';

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    companyId: 'comp-1',
    companyName: 'Innovate Inc.',
    postedBy: 'recruiter-1',
    title: 'Frontend Developer',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'IT',
    requiredSkills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    location: { city: 'Pune', remoteAllowed: true },
    salaryRange: { min: 800000, max: 1200000, currency: 'INR' },
    description: 'Join our team to build beautiful and performant web applications using the latest frontend technologies. You will work on our flagship product and contribute to a high-quality user experience.',
    openings: 2,
    screeningQuestions: ['What is your favorite React feature and why?'],
    isActive: true,
    createdAt: {} as any, 
    updatedAt: {} as any,
  },
  {
    id: 'job-2',
    companyId: 'comp-2',
    companyName: 'DataDriven Co.',
    postedBy: 'recruiter-2',
    title: 'Data Scientist',
    roleType: 'full-time',
    experienceLevel: '3+',
    domain: 'Data Science',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch', 'SQL'],
    location: { city: 'Bangalore', remoteAllowed: false },
    description: 'Work on cutting-edge machine learning models for our platform. You will be responsible for developing and deploying models that impact millions of users.',
    openings: 1,
    screeningQuestions: ['Describe a challenging data project you have worked on.'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-3',
    companyId: 'comp-3',
    companyName: 'Creative Solutions',
    postedBy: 'recruiter-3',
    title: 'UX/UI Designer Intern',
    roleType: 'internship',
    experienceLevel: 'fresher',
    domain: 'Design',
    requiredSkills: ['Figma', 'Adobe XD', 'User Research'],
    location: { city: 'Remote', remoteAllowed: true },
    salaryRange: { min: 20000, max: 25000, currency: 'INR' },
    description: 'A great opportunity for a creative mind to learn and grow. You will work alongside our senior designers on exciting new projects.',
    openings: 3,
    screeningQuestions: ['Share your portfolio link.', 'What design principle is most important to you?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-4',
    companyId: 'comp-1',
    companyName: 'Innovate Inc.',
    postedBy: 'recruiter-1',
    title: 'Backend Engineer (Node.js)',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'IT',
    requiredSkills: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    location: { city: 'Pune', remoteAllowed: true },
    salaryRange: { min: 900000, max: 1400000, currency: 'INR' },
    description: 'Build and maintain the backbone of our services. You will be responsible for designing, developing, and deploying robust and scalable server-side applications.',
    openings: 1,
    screeningQuestions: [],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-5',
    companyId: 'comp-4',
    companyName: 'HealthWell',
    postedBy: 'recruiter-4',
    title: 'Mobile App Developer (React Native)',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'Mobile Development',
    requiredSkills: ['React Native', 'iOS', 'Android', 'GraphQL'],
    location: { city: 'Hyderabad', remoteAllowed: false },
    salaryRange: { min: 1000000, max: 1500000, currency: 'INR' },
    description: 'Develop and enhance our cross-platform mobile application that helps thousands of users manage their health.',
    openings: 2,
    screeningQuestions: ['Have you published any apps on the App Store or Google Play?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-6',
    companyId: 'comp-5',
    companyName: 'FinTech Futures',
    postedBy: 'recruiter-5',
    title: 'DevOps Engineer',
    roleType: 'full-time',
    experienceLevel: '3+',
    domain: 'IT',
    requiredSkills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
    location: { city: 'Mumbai', remoteAllowed: true },
    salaryRange: { min: 1500000, max: 2500000, currency: 'INR' },
    description: 'Manage and scale our cloud infrastructure. You will be responsible for automating our deployment pipelines and ensuring high availability.',
    openings: 1,
    screeningQuestions: ['How do you approach infrastructure as code?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-7',
    companyId: 'comp-2',
    companyName: 'DataDriven Co.',
    postedBy: 'recruiter-2',
    title: 'Data Analyst Intern',
    roleType: 'internship',
    experienceLevel: 'fresher',
    domain: 'Data Science',
    requiredSkills: ['SQL', 'Excel', 'Tableau', 'Power BI'],
    location: { city: 'Bangalore', remoteAllowed: false },
    description: 'Analyze large datasets to extract meaningful insights and support our business decisions. A great entry-level role for aspiring data professionals.',
    openings: 4,
    screeningQuestions: ['What is your experience with SQL joins?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-8',
    companyId: 'comp-3',
    companyName: 'Creative Solutions',
    postedBy: 'recruiter-3',
    title: 'Content Marketing Manager',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'Marketing',
    requiredSkills: ['SEO', 'Content Strategy', 'Copywriting', 'Google Analytics'],
    location: { city: 'Delhi', remoteAllowed: true },
    salaryRange: { min: 600000, max: 900000, currency: 'INR' },
    description: 'Lead our content marketing efforts to drive brand awareness and generate leads. You will manage our blog, social media, and email campaigns.',
    openings: 1,
    screeningQuestions: ['Share a link to a content piece you are proud of.'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-9',
    companyId: 'comp-1',
    companyName: 'Innovate Inc.',
    postedBy: 'recruiter-1',
    title: 'Full Stack Developer',
    roleType: 'full-time',
    experienceLevel: '3+',
    domain: 'IT',
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'AWS'],
    location: { city: 'Pune', remoteAllowed: false },
    salaryRange: { min: 1800000, max: 2800000, currency: 'INR' },
    description: 'We are looking for an experienced Full Stack Developer to work on both our frontend and backend systems.',
    openings: 1,
    screeningQuestions: ['Describe your experience with microservices architecture.'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-10',
    companyId: 'comp-6',
    companyName: 'CyberSecure',
    postedBy: 'recruiter-6',
    title: 'Cyber Security Analyst',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'Cybersecurity',
    requiredSkills: ['Network Security', 'SIEM', 'Penetration Testing', 'Python'],
    location: { city: 'Chennai', remoteAllowed: false },
    description: 'Join our security operations center to monitor, detect, and respond to cyber threats. Protect our infrastructure and client data.',
    openings: 3,
    screeningQuestions: ['What are the common types of cyber attacks?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-11',
    companyId: 'comp-4',
    companyName: 'HealthWell',
    postedBy: 'recruiter-4',
    title: 'Product Manager',
    roleType: 'full-time',
    experienceLevel: '3+',
    domain: 'Product Management',
    requiredSkills: ['Agile', 'Roadmap Planning', 'User Research', 'JIRA'],
    location: { city: 'Hyderabad', remoteAllowed: true },
    description: 'Define the product vision and roadmap for our mobile health platform. You will work closely with engineering, design, and marketing teams.',
    openings: 1,
    screeningQuestions: ['How do you prioritize features for a product release?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
  {
    id: 'job-12',
    companyId: 'comp-5',
    companyName: 'FinTech Futures',
    postedBy: 'recruiter-5',
    title: 'QA Automation Engineer',
    roleType: 'full-time',
    experienceLevel: '1-3',
    domain: 'IT',
    requiredSkills: ['Selenium', 'Cypress', 'JavaScript', 'API Testing'],
    location: { city: 'Mumbai', remoteAllowed: false },
    salaryRange: { min: 700000, max: 1100000, currency: 'INR' },
    description: 'Design and develop automated testing frameworks to ensure the quality of our financial software products. Work in a fast-paced agile environment.',
    openings: 2,
    screeningQuestions: ['What is the difference between Selenium and Cypress?'],
    isActive: true,
    createdAt: {} as any,
    updatedAt: {} as any,
  },
];
